Description: Create EC2 Instance

Parameters:
  InstanceTypeParameter:
    Description: Select Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small or m1.large. Default is t2.micro

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: ami-06cffe063efe892ad 
